"""
Конфигурационный файл валютных пар для проекта AbsCur3.
Обновленный список всех пар, доступной через Twelve Data API.
Всего пар: 296
"""

CURRENCY_PAIRS = [
    # Format: (symbol, currency_group, currency_base, currency_quote)
    ("AED/USD", "Exotic", "UAE Dirham", "US Dollar"),
    ("AFN/USD", "Minor", "Afghanistan Afghani", "US Dollar"),
    ("ARS/USD", "Exotic", "Argentinian Peso", "US Dollar"),
    ("AUD/CAD", "Minor", "Australian Dollar", "Canadian Dollar"),
    ("AUD/CHF", "Minor", "Australian Dollar", "Swiss Franc"),
    ("AUD/EUR", "Minor", "Australian Dollar", "Euro"),
    ("AUD/GBP", "Minor", "Australian Dollar", "British Pound"),
    ("AUD/JPY", "Minor", "Australian Dollar", "Japanese Yen"),
    ("AUD/NZD", "Minor", "Australian Dollar", "New Zealand Dollar"),
    ("AUD/USD", "Major", "Australian Dollar", "US Dollar"),
    ("AZN/RUB", "Minor", "Azerbaijani Manat", "Russian Ruble"),
    ("BGN/RUB", "Minor", "Bulgarian Lev", "Russian Ruble"),
    ("BHD/INR", "Minor", "Baharain Dinar", "Indian Rupee"),
    ("BMD/USD", "Major", "Bermudian Dollar", "US Dollar"),
    ("BOB/USD", "Exotic", "Bolivian Boliviano", "US Dollar"),
    ("BRL/USD", "Exotic", "Brazil Real", "US Dollar"),
    ("BYN/USD", "Minor", "Belarusian Ruble", "US Dollar"),
    ("CAD/AUD", "Minor", "Canadian Dollar", "Australian Dollar"),
    ("CAD/CHF", "Minor", "Canadian Dollar", "Swiss Franc"),
    ("CAD/COP", "Minor", "Canadian Dollar", "Colombian Peso"),
    ("CAD/EUR", "Minor", "Canadian Dollar", "Euro"),
    ("CAD/GBP", "Minor", "Canadian Dollar", "British Pound"),
    ("CAD/JPY", "Minor", "Canadian Dollar", "Japanese Yen"),
    ("CAD/NZD", "Minor", "Canadian Dollar", "New Zealand Dollar"),
    ("CAD/USD", "Major", "Canadian Dollar", "US Dollar"),
    ("CHF/AUD", "Minor", "Swiss Franc", "Australian Dollar"),
    ("CHF/CAD", "Minor", "Swiss Franc", "Canadian Dollar"),
    ("CHF/EUR", "Minor", "Swiss Franc", "Euro"),
    ("CHF/GBP", "Minor", "Swiss Franc", "British Pound"),
    ("CHF/JPY", "Minor", "Swiss Franc", "Japanese Yen"),
    ("CHF/NZD", "Minor", "Swiss Franc", "New Zealand Dollar"),
    ("CHF/USD", "Major", "Swiss Franc", "US Dollar"),
    ("CLP/USD", "Exotic", "Chilean Peso", "US Dollar"),
    ("CNY/CNH", "Minor", "Chinese Yuan", "Chinese Yuan (Offshore)"),
    ("CNY/MNT", "Minor", "Chinese Yuan", "Mongolian Tugrik"),
    ("CNY/USD", "Exotic", "Chinese Yuan", "US Dollar"),
    ("COP/USD", "Exotic", "Colombian Peso", "US Dollar"),
    ("CZK/PLN", "Minor", "Czech Koruna", "Polish Zloty"),
    ("CZK/USD", "Minor", "Czech Koruna", "US Dollar"),
    ("DKK/USD", "Exotic", "Danish Krone", "US Dollar"),
    ("EGP/USD", "Exotic", "Egyptian Pound", "US Dollar"),
    ("EUR/AMD", "Minor", "Euro", "Armenian Dram"),
    ("EUR/AOA", "Minor", "Euro", "Angolan kwanza"),
    ("EUR/AUD", "Minor", "Euro", "Australian Dollar"),
    ("EUR/AZN", "Exotic", "Euro", "Azerbaijani Manat"),
    ("EUR/CAD", "Minor", "Euro", "Canadian Dollar"),
    ("EUR/CHF", "Minor", "Euro", "Swiss Franc"),
    ("EUR/GBP", "Minor", "Euro", "British Pound"),
    ("EUR/GEL", "Minor", "Euro", "Georgian lari"),
    ("EUR/JPY", "Minor", "Euro", "Japanese Yen"),
    ("EUR/MZN", "Exotic", "Euro", "Mozambican Metical"),
    ("EUR/NZD", "Minor", "Euro", "New Zealand Dollar"),
    ("EUR/TJS", "Minor", "Euro", "Tajikistani somoni"),
    ("EUR/USD", "Major", "Euro", "US Dollar"),
    ("FJD/USD", "Exotic", "Fiji Dollar", "US Dollar"),
    ("FKP/USD", "Major", "Falkland Islands Pound", "US Dollar"),
    ("GBP/AUD", "Minor", "British Pound", "Australian Dollar"),
    ("GBP/CAD", "Minor", "British Pound", "Canadian Dollar"),
    ("GBP/CHF", "Minor", "British Pound", "Swiss Franc"),
    ("GBP/EUR", "Minor", "British Pound", "Euro"),
    ("GBP/JPY", "Minor", "British Pound", "Japanese Yen"),
    ("GBP/NPR", "Minor", "British Pound", "Nepalese Rupee"),
    ("GBP/NZD", "Minor", "British Pound", "New Zealand Dollar"),
    ("GBP/USD", "Major", "British Pound", "US Dollar"),
    ("GEL/RUB", "Minor", "Georgian lari", "Russian Ruble"),
    ("GHS/USD", "Exotic", "Ghanaian Cedi", "US Dollar"),
    ("GIP/USD", "Major", "Gibraltar Pound", "US Dollar"),
    ("HKD/USD", "Exotic", "Hong Kong Dollar", "US Dollar"),
    ("HUF/EUR", "Minor", "Hungarian Forint", "Euro"),
    ("HUF/USD", "Minor", "Hungarian Forint", "US Dollar"),
    ("IDR/AUD", "Minor", "Indonesian Rupiah", "Australian Dollar"),
    ("IDR/CHF", "Minor", "Indonesian Rupiah", "Swiss Franc"),
    ("IDR/EUR", "Minor", "Indonesian Rupiah", "Euro"),
    ("IDR/GBP", "Minor", "Indonesian Rupiah", "British Pound"),
    ("IDR/USD", "Minor", "Indonesian Rupiah", "US Dollar"),
    ("ILS/BGN", "Minor", "Israeli Shekel", "Bulgarian Lev"),
    ("ILS/COP", "Minor", "Israeli Shekel", "Colombian Peso"),
    ("ILS/PEN", "Minor", "Israeli Shekel", "Peru Sol"),
    ("ILS/UAH", "Minor", "Israeli Shekel", "Ukrainian Hryvnia"),
    ("ILS/USD", "Exotic", "Israeli Shekel", "US Dollar"),
    ("ILS/UYU", "Minor", "Israeli Shekel", "Uruguayan Peso"),
    ("INR/BRL", "Minor", "Indian Rupee", "Brazil Real"),
    ("INR/USD", "Exotic", "Indian Rupee", "US Dollar"),
    ("IQD/USD", "Minor", "Iraqi Dinar", "US Dollar"),
    ("IRR/USD", "Minor", "Iranian Rial", "US Dollar"),
    ("JOD/EUR", "Minor", "Jordan Dinar", "Euro"),
    ("JOD/GBP", "Minor", "Jordan Dinar", "British Pound"),
    ("JOD/USD", "Minor", "Jordan Dinar", "US Dollar"),
    ("JPY/AUD", "Minor", "Japanese Yen", "Australian Dollar"),
    ("JPY/CAD", "Minor", "Japanese Yen", "Canadian Dollar"),
    ("JPY/CHF", "Minor", "Japanese Yen", "Swiss Franc"),
    ("JPY/EUR", "Minor", "Japanese Yen", "Euro"),
    ("JPY/GBP", "Minor", "Japanese Yen", "British Pound"),
    ("JPY/NZD", "Minor", "Japanese Yen", "New Zealand Dollar"),
    ("JPY/TRY", "Minor", "Japanese Yen", "Turkish Lira"),
    ("JPY/USD", "Major", "Japanese Yen", "US Dollar"),
    ("KGS/RUB", "Minor", "Kyrgyzstan som", "Russian Ruble"),
    ("KRW/USD", "Exotic", "Korean Won", "US Dollar"),
    ("KWD/EUR", "Minor", "Kuwaiti Dinar", "Euro"),
    ("KWD/MYR", "Minor", "Kuwaiti Dinar", "Malaysian Ringgit"),
    ("KWD/SGD", "Minor", "Kuwaiti Dinar", "Singapore Dollar"),
    ("KWD/USD", "Minor", "Kuwaiti Dinar", "US Dollar"),
    ("KYD/USD", "Exotic", "Cayman Islands Dollar", "US Dollar"),
    ("MDL/RUB", "Minor", "Moldovan Leu", "Russian Ruble"),
    ("MXN/USD", "Exotic", "Mexican Peso", "US Dollar"),
    ("MYR/USD", "Minor", "Malaysian Ringgit", "US Dollar"),
    ("NIO/USD", "Exotic", "Nicaraguan Cordoba", "US Dollar"),
    ("NOK/USD", "Exotic", "Norwegian Krone", "US Dollar"),
    ("NZD/AUD", "Minor", "New Zealand Dollar", "Australian Dollar"),
    ("NZD/CAD", "Minor", "New Zealand Dollar", "Canadian Dollar"),
    ("NZD/CHF", "Minor", "New Zealand Dollar", "Swiss Franc"),
    ("NZD/EUR", "Minor", "New Zealand Dollar", "Euro"),
    ("NZD/GBP", "Minor", "New Zealand Dollar", "British Pound"),
    ("NZD/JPY", "Minor", "New Zealand Dollar", "Japanese Yen"),
    ("NZD/USD", "Major", "New Zealand Dollar", "US Dollar"),
    ("PEN/USD", "Exotic", "Peru Sol", "US Dollar"),
    ("PHP/USD", "Minor", "Philippine Peso", "US Dollar"),
    ("PLN/UAH", "Minor", "Polish Zloty", "Ukrainian Hryvnia"),
    ("PLN/USD", "Exotic", "Polish Zloty", "US Dollar"),
    ("PYG/USD", "Exotic", "Paraguayan Guarani", "US Dollar"),
    ("RUB/AMD", "Minor", "Russian Ruble", "Armenian Dram"),
    ("RUB/BRL", "Minor", "Russian Ruble", "Brazil Real"),
    ("RUB/USD", "Exotic", "Russian Ruble", "US Dollar"),
    ("RUB/VND", "Minor", "Russian Ruble", "Vietnamese Dong"),
    ("SAR/USD", "Exotic", "Saudi Riyal", "US Dollar"),
    ("SDR/RUB", "Minor", "Special Drawing Rights", "Russian Ruble"),
    ("SDR/TRY", "Minor", "Special Drawing Rights", "Turkish Lira"),
    ("SGD/KWD", "Minor", "Singapore Dollar", "Kuwaiti Dinar"),
    ("SGD/USD", "Exotic", "Singapore Dollar", "US Dollar"),
    ("SHP/USD", "Major", "Saint Helena Pound", "US Dollar"),
    ("SYP/USD", "Minor", "Syrian Pound", "US Dollar"),
    ("THB/GBP", "Minor", "Thai Baht", "British Pound"),
    ("THB/USD", "Minor", "Thai Baht", "US Dollar"),
    ("TJS/RUB", "Minor", "Tajikistani somoni", "Russian Ruble"),
    ("TRY/UAH", "Minor", "Turkish Lira", "Ukrainian Hryvnia"),
    ("TRY/USD", "Exotic", "Turkish Lira", "US Dollar"),
    ("TWD/USD", "Exotic", "Taiwan Dollar", "US Dollar"),
    ("UAH/KZT", "Minor", "Ukrainian Hryvnia", "Kazakh Tenge"),
    ("UAH/PLN", "Minor", "Ukrainian Hryvnia", "Polish Zloty"),
    ("UAH/USD", "Minor", "Ukrainian Hryvnia", "US Dollar"),
    ("USD/AED", "Exotic", "US Dollar", "UAE Dirham"),
    ("USD/AFN", "Minor", "US Dollar", "Afghanistan Afghani"),
    ("USD/ALL", "Exotic", "US Dollar", "Albanian Lek"),
    ("USD/AMD", "Exotic", "US Dollar", "Armenian Dram"),
    ("USD/AOA", "Minor", "US Dollar", "Angolan kwanza"),
    ("USD/ARS", "Exotic", "US Dollar", "Argentinian Peso"),
    ("USD/AUD", "Major", "US Dollar", "Australian Dollar"),
    ("USD/AWG", "Major", "US Dollar", "Aruban Florin"),
    ("USD/AZN", "Exotic", "US Dollar", "Azerbaijani Manat"),
    ("USD/BAM", "Exotic", "US Dollar", "Bosnian and Herzegovina Convertible Mark"),
    ("USD/BBD", "Exotic", "US Dollar", "Barbadian Dollar"),
    ("USD/BDT", "Exotic", "US Dollar", "Bangladeshi Taka"),
    ("USD/BGN", "Exotic", "US Dollar", "Bulgarian Lev"),
    ("USD/BHD", "Exotic", "US Dollar", "Baharain Dinar"),
    ("USD/BIF", "Exotic", "US Dollar", "Burundian Franc"),
    ("USD/BND", "Exotic", "US Dollar", "Brunei Dollar"),
    ("USD/BOB", "Exotic", "US Dollar", "Bolivian Boliviano"),
    ("USD/BRL", "Exotic", "US Dollar", "Brazil Real"),
    ("USD/BSD", "Exotic", "US Dollar", "Bahamas Dollar"),
    ("USD/BTN", "Major", "US Dollar", "Bhutanese Ngultrum"),
    ("USD/BWP", "Exotic", "US Dollar", "Botswana Pula"),
    ("USD/BZD", "Exotic", "US Dollar", "Belize Dollar"),
    ("USD/CAD", "Major", "US Dollar", "Canadian Dollar"),
    ("USD/CDF", "Major", "US Dollar", "Congolese Franc"),
    ("USD/CHF", "Major", "US Dollar", "Swiss Franc"),
    ("USD/CLP", "Exotic", "US Dollar", "Chilean Peso"),
    ("USD/CNH", "Exotic", "US Dollar", "Chinese Yuan (Offshore)"),
    ("USD/CNY", "Exotic", "US Dollar", "Chinese Yuan"),
    ("USD/COP", "Exotic", "US Dollar", "Colombian Peso"),
    ("USD/CRC", "Exotic", "US Dollar", "Costa Rican Colon"),
    ("USD/CUP", "Exotic", "US Dollar", "Cuban Peso"),
    ("USD/CVE", "Major", "US Dollar", "Cape Verdean Escudo"),
    ("USD/CZK", "Exotic", "US Dollar", "Czech Koruna"),
    ("USD/DJF", "Exotic", "US Dollar", "Djiboutian Franc"),
    ("USD/DKK", "Exotic", "US Dollar", "Danish Krone"),
    ("USD/DOP", "Exotic", "US Dollar", "Dominican Peso"),
    ("USD/DZD", "Exotic", "US Dollar", "Algerian Dinar"),
    ("USD/EGP", "Exotic", "US Dollar", "Egyptian Pound"),
    ("USD/ETB", "Exotic", "US Dollar", "Ethiopian Birr"),
    ("USD/EUR", "Major", "US Dollar", "Euro"),
    ("USD/FJD", "Exotic", "US Dollar", "Fiji Dollar"),
    ("USD/GBP", "Major", "US Dollar", "British Pound"),
    ("USD/GEL", "Exotic", "US Dollar", "Georgian lari"),
    ("USD/GHS", "Exotic", "US Dollar", "Ghanaian Cedi"),
    ("USD/GMD", "Exotic", "US Dollar", "Gambian Dalasi"),
    ("USD/GNF", "Exotic", "US Dollar", "Guinean Franc"),
    ("USD/GTQ", "Exotic", "US Dollar", "Guatemalan Quetzal"),
    ("USD/GYD", "Major", "US Dollar", "Guyanese Dollar"),
    ("USD/HKD", "Exotic", "US Dollar", "Hong Kong Dollar"),
    ("USD/HNL", "Exotic", "US Dollar", "Honduran Lempira"),
    ("USD/HTG", "Exotic", "US Dollar", "Haitian Gourde"),
    ("USD/HUF", "Exotic", "US Dollar", "Hungarian Forint"),
    ("USD/IDR", "Exotic", "US Dollar", "Indonesian Rupiah"),
    ("USD/ILS", "Exotic", "US Dollar", "Israeli Shekel"),
    ("USD/INR", "Exotic", "US Dollar", "Indian Rupee"),
    ("USD/IQD", "Exotic", "US Dollar", "Iraqi Dinar"),
    ("USD/IRR", "Exotic", "US Dollar", "Iranian Rial"),
    ("USD/ISK", "Exotic", "US Dollar", "Icelandic Krona"),
    ("USD/JMD", "Exotic", "US Dollar", "Jamaican Dollar"),
    ("USD/JOD", "Exotic", "US Dollar", "Jordan Dinar"),
    ("USD/JPY", "Major", "US Dollar", "Japanese Yen"),
    ("USD/KES", "Exotic", "US Dollar", "Kenyan Shilling"),
    ("USD/KHR", "Exotic", "US Dollar", "Cambodian Riel"),
    ("USD/KMF", "Exotic", "US Dollar", "Comorian Franc"),
    ("USD/KRW", "Exotic", "US Dollar", "Korean Won"),
    ("USD/KWD", "Exotic", "US Dollar", "Kuwaiti Dinar"),
    ("USD/KZT", "Exotic", "US Dollar", "Kazakh Tenge"),
    ("USD/LAK", "Exotic", "US Dollar", "Lao Kip"),
    ("USD/LBP", "Exotic", "US Dollar", "Lebanese Pound"),
    ("USD/LKR", "Exotic", "US Dollar", "Sri Lankan Rupee"),
    ("USD/LRD", "Major", "US Dollar", "Liberian Dollar"),
    ("USD/LSL", "Exotic", "US Dollar", "Lesotho loti"),
    ("USD/LYD", "Exotic", "US Dollar", "Libyan Dinar"),
    ("USD/MAD", "Exotic", "US Dollar", "Moroccan Dirham"),
    ("USD/MDL", "Exotic", "US Dollar", "Moldovan Leu"),
    ("USD/MGA", "Exotic", "US Dollar", "Malagasy Ariary"),
    ("USD/MKD", "Exotic", "US Dollar", "Macedonian Denar"),
    ("USD/MMK", "Exotic", "US Dollar", "Myanmar kyat"),
    ("USD/MNT", "Minor", "US Dollar", "Mongolian Tugrik"),
    ("USD/MOP", "Exotic", "US Dollar", "Macanese Pataca"),
    ("USD/MRU", "Major", "US Dollar", "Mauritanian Ouguiya"),
    ("USD/MUR", "Exotic", "US Dollar", "Mauritian Rupee"),
    ("USD/MVR", "Exotic", "US Dollar", "Maldivian Rufiyaa"),
    ("USD/MWK", "Exotic", "US Dollar", "Malawian Kwacha"),
    ("USD/MXN", "Exotic", "US Dollar", "Mexican Peso"),
    ("USD/MYR", "Exotic", "US Dollar", "Malaysian Ringgit"),
    ("USD/MZN", "Exotic", "US Dollar", "Mozambican Metical"),
    ("USD/NAD", "Exotic", "US Dollar", "Namibian Dollar"),
    ("USD/NGN", "Exotic", "US Dollar", "Nigerian Naira"),
    ("USD/NIO", "Exotic", "US Dollar", "Nicaraguan Cordoba"),
    ("USD/NOK", "Exotic", "US Dollar", "Norwegian Krone"),
    ("USD/NPR", "Exotic", "US Dollar", "Nepalese Rupee"),
    ("USD/NZD", "Major", "US Dollar", "New Zealand Dollar"),
    ("USD/OMR", "Exotic", "US Dollar", "Omani Rial"),
    ("USD/PAB", "Exotic", "US Dollar", "Panamanian Balboa"),
    ("USD/PEN", "Exotic", "US Dollar", "Peru Sol"),
    ("USD/PGK", "Exotic", "US Dollar", "Papua New Guinean kina"),
    ("USD/PHP", "Exotic", "US Dollar", "Philippine Peso"),
    ("USD/PKR", "Exotic", "US Dollar", "Pakistani Rupee"),
    ("USD/PLN", "Exotic", "US Dollar", "Polish Zloty"),
    ("USD/PYG", "Exotic", "US Dollar", "Paraguayan Guarani"),
    ("USD/QAR", "Exotic", "US Dollar", "Qatari Riyal"),
    ("USD/RON", "Exotic", "US Dollar", "Romanian Leu"),
    ("USD/RSD", "Exotic", "US Dollar", "Serbian Dinar"),
    ("USD/RUB", "Minor", "US Dollar", "Russian Ruble"),
    ("USD/RWF", "Exotic", "US Dollar", "Rwandan Franc"),
    ("USD/SAR", "Exotic", "US Dollar", "Saudi Riyal"),
    ("USD/SBD", "Major", "US Dollar", "Solomon Islands Dollar"),
    ("USD/SCR", "Exotic", "US Dollar", "Seychelles Rupee"),
    ("USD/SDG", "Exotic", "US Dollar", "Sudanese Pound"),
    ("USD/SEK", "Exotic", "US Dollar", "Swedish Krona"),
    ("USD/SGD", "Exotic", "US Dollar", "Singapore Dollar"),
    ("USD/SLE", "Major", "US Dollar", "Sierra Leonean Leone"),
    ("USD/SOS", "Exotic", "US Dollar", "Somali Shilling"),
    ("USD/SRD", "Major", "US Dollar", "Surinamese Dollar"),
    ("USD/STN", "Major", "US Dollar", "São Tomé and Príncipe Dobra"),
    ("USD/SVC", "Exotic", "US Dollar", "El Salvador Colon"),
    ("USD/SYP", "Exotic", "US Dollar", "Syrian Pound"),
    ("USD/SZL", "Exotic", "US Dollar", "Swazi Lilangeni"),
    ("USD/THB", "Exotic", "US Dollar", "Thai Baht"),
    ("USD/TJS", "Minor", "US Dollar", "Tajikistani somoni"),
    ("USD/TMT", "Minor", "US Dollar", "Turkmenistan manat"),
    ("USD/TND", "Exotic", "US Dollar", "Tunisian Dinar"),
    ("USD/TOP", "Major", "US Dollar", "Tongan Pa'anga"),
    ("USD/TRY", "Exotic", "US Dollar", "Turkish Lira"),
    ("USD/TTD", "Exotic", "US Dollar", "Trinidad Dollar"),
    ("USD/TWD", "Exotic", "US Dollar", "Taiwan Dollar"),
    ("USD/TZS", "Exotic", "US Dollar", "Tanzanian Shilling"),
    ("USD/UAH", "Exotic", "US Dollar", "Ukrainian Hryvnia"),
    ("USD/UGX", "Exotic", "US Dollar", "Ugandan Shilling"),
    ("USD/UYU", "Exotic", "US Dollar", "Uruguayan Peso"),
    ("USD/UZS", "Exotic", "US Dollar", "Uzbekistani Sum"),
    ("USD/VES", "Major", "US Dollar", "Venezuelan Bolívar Soberano"),
    ("USD/VND", "Exotic", "US Dollar", "Vietnamese Dong"),
    ("USD/VUV", "Exotic", "US Dollar", "Vanuatu vatu"),
    ("USD/WST", "Major", "US Dollar", "Samoan Tala"),
    ("USD/XAF", "Exotic", "US Dollar", "Central African CFA franc"),
    ("USD/XCD", "Exotic", "US Dollar", "East Caribbean Dollar"),
    ("USD/XOF", "Exotic", "US Dollar", "West African CFA franc"),
    ("USD/XPF", "Exotic", "US Dollar", "French Pacific Franc"),
    ("USD/YER", "Exotic", "US Dollar", "Yemeni Rial"),
    ("USD/ZAR", "Exotic", "US Dollar", "South African Rand"),
    ("USD/ZMW", "Exotic", "US Dollar", "Zambia Kwacha"),
    ("UYU/USD", "Exotic", "Uruguayan Peso", "US Dollar"),
    ("VND/USD", "Minor", "Vietnamese Dong", "US Dollar"),
    ("XDR/USD", "Major", "Special Drawing Rights", "US Dollar"),
    ("ZAR/USD", "Exotic", "South African Rand", "US Dollar"),
]

# Утилитарные функции для работы со списком пар
def get_all_symbols():
    """Возвращает список всех символов (пар)"""
    return [pair[0] for pair in CURRENCY_PAIRS]

def get_symbols_by_group(group):
    """Возвращает символы по группе (Major/Minor/Exotic)"""
    return [pair[0] for pair in CURRENCY_PAIRS if pair[1] == group]

def get_major_pairs():
    """Возвращает список мажорных пар"""
    return get_symbols_by_group("Major")

def get_minor_pairs():
    """Возвращает список минорных пар"""
    return get_symbols_by_group("Minor")

def get_exotic_pairs():
    """Возвращает список экзотических пар"""
    return get_symbols_by_group("Exotic")

def get_pair_info(symbol):
    """Возвращает информацию о конкретной паре"""
    for pair in CURRENCY_PAIRS:
        if pair[0] == symbol:
            return {
                "symbol": pair[0],
                "currency_group": pair[1],
                "currency_base": pair[2],
                "currency_quote": pair[3]
            }
    return None

# Дополнительные константы для удобства
MAJOR_PAIRS = get_major_pairs()
MINOR_PAIRS = get_minor_pairs()
EXOTIC_PAIRS = get_exotic_pairs()
ALL_SYMBOLS = get_all_symbols()

if __name__ == "__main__":
    # Тестовая проверка
    print(f"Всего пар: {len(ALL_SYMBOLS)}")
    print(f"Мажорных пар: {len(MAJOR_PAIRS)}")
    print(f"Минорных пар: {len(MINOR_PAIRS)}")
    print(f"Экзотических пар: {len(EXOTIC_PAIRS)}")
    print(f"\nПример информации по USD/RUB: {get_pair_info('USD/RUB')}")